name: hype49sneakers
description: A sneaker shopping app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/shoe_thumb_1.jpeg
    - assets/shoe_thumb_2.jpeg
    - assets/shoe_thumb_3.jpeg
    - assets/shoe_thumb_4.jpeg
    - assets/shoe_thumb_5.jpeg
    - assets/shoe_thumb_6.jpeg
    - assets/shoe_thumb_7.jpeg
    - assets/bmb.jpg
    - assets/jacket.jpeg
    - assets/watch.jpeg
    - assets/categories/running.jpg
    - assets/categories/basketball.jpg
    - assets/categories/lifestyle.jpg
    - assets/categories/training.jpg
    - assets/brands/nike.png
    - assets/brands/adidas.png
    - assets/brands/puma.png
    - assets/brands/reebok.png
    - assets/brands/newbalance.png
    - assets/brands/jordan.png
